#! /bin/bash

makeCompiler(){
	cd ./compile
	make -j4
	cd ..
}

makeAssembler(){
	cd ./ass
	make -j4
	cd ..
}

makeLinker(){
	cd ./lit
	make -j4
	cd ..
}

makeLibary(){
	cd ./stdlib
	../ass/lsca start.s
	../ass/lsca stdlib.s
	cd ..
}

if [ $1x == "ass"x ]
then
	makeAssembler
elif [ $1x == "cmp"x ]
then
	makeCompiler
elif [ $1x == "lit"x ]
then
	makeLinker
elif [ $1x == "lib"x ]
then
	makeLibary
elif [ $1x == "pre"x ]
then
	cd ./preproc
	make
elif [ $1x == "clear"x ]
then
	cd ./compile
	make clear
	cd ../ass
	make clear
	cd ../lit
	make clear
	cd ../preproc
	make clear
	cd ../stdlib
	rm -f *.o
elif [ $1x == "install"x ]
then
	echo "编译编译器模块..."
	makeCompiler
	echo "编译汇编器模块..."
	makeAssembler
	echo "编译链接器模块..."
	makeLinker
	echo "编译标准库模块...."
	makeLibary
	echo "链接主程序..."
	g++ main.cpp -o lsc -std=c++11	
	echo "复制依赖文件到目录..."
	sudo mkdir /usr/include/lsc
	sudo cp ./stdlib/lscio.h  /usr/include/lsc/lscio.h
	sudo cp ./stdlib/start.o /usr/include/lsc/start.o
	sudo cp ./stdlib/stdlib.o /usr/include/lsc/stdlib.o
	echo "安装完成"
elif [ $1x == "uninstall"x ]
then
	echo "删除依赖文件..."
	sudo rm -rf /usr/include/lsc
	echo "卸载完成"
else
	echo ""
	echo "用法: ./makeProject [参数]"
	echo "参数可以选择以下值:"
	echo "install   编译并安装lsc编译系统"
	echo "unistall  卸载lsc编译系统"
	echo "ass       编译汇编器"
	echo "cmp       编译编译器"
	echo "lit       编译连接器"
	echo "lib       编译标准库"
	echo "clear     清除编译中间结果"	
fi


