#! /bin/bash

makeCompiler(){
	cd ./compile
	make -j4
	cd ..
}

makeAssembler(){
	cd ./ass
	make -j4
	cd ..
}

makeLinker(){
	cd ./lit
	make -j4
	cd ..
}

makeLibary(){
	cd ./stdlib
	make
	cd ..
}

makeMain(){
	g++ main.cpp -o lsc -std=c++11 -Wall -Wextra
}

makeLar(){
	cd ./lar
	make -j4
	cd ..
}

makeAll(){
	echo "编译编译器模块..."
	makeCompiler
	echo "编译汇编器模块..."
	makeAssembler
	echo "编译链接器模块..."
	makeLinker
	echo "编译压缩模块..."
	makeLar
	echo "编译标准库模块...."
	makeLibary
	echo "链接主程序..."
	makeMain
	echo "编译完成"
}

makeClear(){
	cd ./compile
	make clear
	cd ../ass
	make clear
	cd ../lit
	make clear
	cd ../lar
	make clear
	cd ../stdlib
	make clear
	cd ..
}

copyStdLib(){
	sudo cp ./stdlib/lscio.h   /usr/include/lsc/lscio.h
	sudo cp ./stdlib/lsclib.h  /usr/include/lsc/lsclib.h
	sudo cp ./stdlib/start.o   /usr/include/lsc/start.o
	sudo cp ./stdlib/lscore.o  /usr/include/lsc/lscore.o
	sudo cp ./stdlib/lscio.o   /usr/include/lsc/lscio.o
	sudo cp ./stdlib/lsclib.o  /usr/include/lsc/lsclib.o
}

copyExeFile(){
	sudo cp ./lsc          /usr/local/bin/lsc
	sudo cp ./compile/lscc /usr/local/bin/lscc
	sudo cp ./ass/lsca 	   /usr/local/bin/lsca
	sudo cp ./lit/lscl     /usr/local/bin/lscl
  sudo cp ./lar/lar      /usr/local/bin/lar
}

removeExeFile(){
	sudo rm /usr/local/bin/lsc
	sudo rm /usr/local/bin/lscc
	sudo rm /usr/local/bin/lsca
	sudo rm /usr/local/bin/lscl
	sudo rm /usr/local/bin/lar
}

install(){
	echo "编译项目代码..."
	makeAll

	echo "复制依赖文件到目录..."
	sudo mkdir /usr/include/lsc
	copyStdLib
	copyExeFile

	echo "安装完成"
}

uninstall(){
	echo "删除依赖文件..."
	sudo rm -rf /usr/include/lsc
	removeExeFile
	echo "卸载完成"
}


subCmd=$1

case $subCmd in
	ass)
		makeAssembler
		;;
	cmp)
		makeCompiler
		;;
	lit)
		makeLinker
		;;
	lib)
		makeLibary
		;;
	lar)
		makeLar
		;;
	main)
		makeMain
		;;
	clear)
		makeClear
		;;
	install | i )
		install
		;;
	uninstall | u)
		uninstall
		;;
	reinstall | r)
		uninstall
		install
		;;
	full-reinstall | fr)
		uninstall
		echo "清除编译中间结果..."
		makeClear
		install	
		;;
	all)
		makeAll
		;;
	*)
		echo "无效的参数: $1"
		echo ""
		echo "用法: ./makeProject [参数]"
		echo "参数可以选择以下值:"
		echo "install     编译并安装lsc编译系统"
		echo "uninstall   卸载lsc编译系统"
		echo "reinstall   重装lsc编译系统"
		echo "all         编译整个项目"
		echo "ass         编译汇编器"
		echo "cmp         编译编译器"
		echo "lit         编译连接器"
		echo "lib         编译标准库"
		echo "lar         编译压缩模块"
		echo "main        编译主函数"
		echo "clear       清除编译中间结果"	
		echo ""
		;;
esac


