#! /bin/bash

if [ $1x == "ass"x ]
then
	cd ./ass
    make
elif [ $1x == "compile"x ]
then
	cd ./compile
    make
elif [ $1x == "clear"x ]
then
	cd ./compile
	make clear
	cd ../ass
	make clear
else
	cd ./compile
	make
	cd ../ass
	make
fi